-- create table branches
-- (
--     id          serial primary key,
--     name        varchar(100) not null,
--     description varchar(100) not null,
--     user_id     int,
--     constraint fk_branch_user
--         foreign key (user_id) references users (id)
-- )